name: Docker ci

on:
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile.docker
          fi

  push:
    # Ensure test job passes before pushing image.
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.docker
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-host:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
